on:
  push:
    branches:
      - master

jobs:
  bump-version-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Bump version and commit
        run: |
          git config user.name 'Your Bot'
          git config user.email 'your.bot@example.com'
          npm version patch -m "release: bump version to %s for new features" # 根据实际情况调整为minor或major，并自定义commit message
          git push origin HEAD:master --follow-tags
      - name: Publish to VS Code Marketplace
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }} # 将你的VSCE个人访问令牌存储为GitHub仓库机密
        run: |
          npm install -g vsce # 如果全局未安装vsce，先安装
          vsce publish # 发布插件到VS Code Marketplace

# 注意：VSCE_PAT 变量需要提前在GitHub仓库设置页面中添加为Secrets